name: Race Compatibility SKSE CI - Auto Release

on:
  push:
    branches: [main]

jobs:
  pack:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      tag: ${{ steps.extract_version.outputs.tag }}
      matrix: ${{ steps.pack.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Extract version
        id: extract_version
        run: |
          . .github/scripts/match-string.ps1

          $content = Get-Content xmake.lua -Raw -Encoding UTF8
          $version = Match-String -content $content -pattern 'set_version\("([^"]+)"'
          $tag = "v$version"

          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "tag=$tag" >> $env:GITHUB_OUTPUT

          echo "📘 Version: $version"

      - name: Check if tag exists
        run: |
          $ErrorActionPreference = "Continue"
          git fetch --tags 2>$null
          $tag = "${{ steps.extract_version.outputs.tag }}"
          git rev-parse $tag -- 2>$null
          $ErrorActionPreference = "Stop"

          if ($LASTEXITCODE -eq 0) {
            echo "❌ Tag already exists: $tag"
            exit 1
          } else {
            echo "🏷️ Tag does not exist: $tag"
            exit 0
          }

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          # ref: https://github.com/xmake-io/xmake/blob/dev/.github/workflows/windows.yml
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ runner.os }}

      - name: Pack and Extract Matrix for Publishing
        id: pack
        run: |
          xmake b config
          $output = xmake pack 2>&1
          $packageList = @()
          foreach ($line in ($output -split '\r?\n')) {
              if ($line -match '\[package\]:\s*(.*)') {
                  $jsonStr = $matches[1].Trim()
                  $packageList += ConvertFrom-Json $jsonStr
              }
          }

          if ($packageList.Count -eq 0) {
              Write-Error "❗ No packages found! Aborting workflow."
              exit 1
          }

          $matrixObject = @{ include = @($packageList) }
          $matrixJson = $matrixObject | ConvertTo-Json -Compress

          echo "matrix=$matrixJson" >> $env:GITHUB_OUTPUT
          echo "🗃️ Packed artifacts"
          echo "📊 Matrix: $matrixJson"

      - name: Generate Artifact Attestation
        if: github.event_name == 'push'
        uses: actions/attest@v4
        with:
          subject-path: build/xpack/*.zip

      - name: Upload Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ steps.extract_version.outputs.version }}
          path: build/xpack/*.zip
          if-no-files-found: error

  release:
    permissions:
      contents: write
    needs: pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create Git tag
        run: |
          tag=${{ needs.pack.outputs.tag }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a "${tag}" HEAD -m "Release ${tag}"
          git push origin "${tag}" || (echo "Failed to push tag"; exit 1)

      - name: Generate changelog
        run: |
          url="https://github.com/${{ github.repository }}"
          prev_tag=$(git describe --tags --abbrev=0 --match "v*.*.*" $(git rev-list --tags --skip=1 --max-count=1))
          echo "prev_tag=$prev_tag" >> $GITHUB_OUTPUT
          {
            echo "## What's Changed"
            echo "* release: version ${{ needs.pack.outputs.version }} by @${GITHUB_ACTOR}"
            echo
            echo
            echo "**Full Changelog**: ${url}/compare/${prev_tag}...${{ needs.pack.outputs.tag }}"
          } > CHANGELOG.md

      - name: Download all ZIP artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: List downloaded files
        run: |
          echo "💼 Artifact:"
          ls -R artifact

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.pack.outputs.tag }}
          name: ${{ needs.pack.outputs.tag }}
          body_path: CHANGELOG.md
          files: artifact/**/*.zip

  publish:
    if: github.event_name == 'push'
    needs:
      - pack
      - release
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.pack.outputs.matrix) }}
      fail-fast: false
    name: publish (${{ matrix.name }})

    steps:
      - name: Download Asset from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download "${{ needs.pack.outputs.tag }}" \
            --repo "${{ github.repository }}" \
            --pattern "${{ matrix.filename }}" \
            --dir ./

      - name: Publish to Nexus Mods
        id: publish_nexusmods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.10
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_id: ${{ matrix.file_id }}
          filename: ${{ matrix.filename }}
          version: ${{ needs.pack.outputs.version }}
          display_name: ${{ matrix.name }}
          description: ${{ matrix.description }}
          category: ${{ matrix.category }}
          archive_existing_version: true
          primary_mod_manager_download: ${{ matrix.category == 'main' }}
          allow_mod_manager_download: true
          show_requirements_pop_up: ${{ matrix.category == 'main' }}
          update_mod_version: false

      - name: List Uploaded Files
        shell: bash
        run: |
          echo "✅ Uploaded ${{ matrix.filename }} to Nexus Mods"
          echo "📑 File UID: ${{ steps.publish_nexusmods.outputs.version_id }}"
          echo "📂 Group ID: ${{ matrix.file_id }}"
          echo " SHA256: $(sha256sum "${{ matrix.filename }}" | awk '{print $1}')"
